export interface PricingPlan {
  id: string;
  name: string;
  monthlyPrice: number | null;
  yearlyPrice: number | null;
  yearlyDiscount: number;
  popular: boolean;
  description: string;
  cta: string;
  ctaLink: string;
  ctaVariant: "default" | "outline";
  featureCategory?: string;
  features: string[];
}

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free Forever",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlyDiscount: 0,
    popular: false,
    description: "Perfect for personal use and small projects",
    cta: "Get Started",
    ctaLink: "/",
    ctaVariant: "outline",
    featureCategory: "KEY FEATURES",
    features: [
      "Corteksa Units: Up to X",
      "Up to X Custom Fields",
      "Cortex AI: Up to X",
      "Tasks management",
      "Up to X Kanban boards",
      "Unlimited Email Support (24 hrs)",
      "Up to 3 Free Plan Members",
      "100MB Data Storage",
    ],
  },
  {
    id: "light",
    name: "Light",
    monthlyPrice: 29,
    yearlyPrice: 29,
    yearlyDiscount: 0,
    popular: false,
    description: "For growing teams that need more power",
    cta: "Get Started",
    ctaLink: "/",
    ctaVariant: "outline",
    featureCategory: "EVERYTHING IN FREE +",
    features: [
      "Corteksa Units: Up to X",
      "Custom Fields",
      "Cortex AI Unlimited",
      "Tasks management",
      "Kanban boards",
      "Unlimited Email Support (4 hrs)",
      "Up to X Basic Plan Members",
      "100MB Data Storage",
      "Marketplace Access",
      "Comments and Mentions",
      "Email Integrations",
      "Data Import and Export",
      "Multi-language Support",
      "Smart Dashboard",
    ],
  },
  {
    id: "advanced",
    name: "Advanced",
    monthlyPrice: 79,
    yearlyPrice: 79,
    yearlyDiscount: 0,
    popular: true,
    description: "Advanced features for professional teams",
    cta: "Get Started",
    ctaLink: "/",
    ctaVariant: "default",
    featureCategory: "EVERYTHING IN LIGHT +",
    features: [
      "Corteksa Units Unlimited",
      "Custom Fields (unlimited)",
      "Cortex AI Unlimited",
      "Tasks management (unlimited)",
      "Unlimited Kanban boards",
      "Unlimited Chat Support (2 hrs)",
      "Unlimited Team Members",
      "Unlimited Data Storage",
      "Marketplace Access",
      "Comments and Mentions",
      "Email Integrations",
      "Data Import and Export",
      "Multi-language Support",
      "Smart Dashboard",
      "Document Generation",
      "Workflow Automation",
      "Advanced Permissions",
      "Audit Logging",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthlyPrice: null,
    yearlyPrice: null,
    yearlyDiscount: 0,
    popular: false,
    description: "Flexible pricing for large organizations",
    cta: "Contact Sales",
    ctaLink: "/contact",
    ctaVariant: "outline",
    featureCategory: "EVERYTHING IN ADVANCED +",
    features: [
      "Corteksa Units Unlimited",
      "Custom Fields (unlimited)",
      "Cortex AI Unlimited",
      "Tasks management (unlimited)",
      "Unlimited Kanban boards",
      "Unlimited Team Members",
      "Unlimited Data Storage",
      "Marketplace Access",
      "Comments and Mentions",
      "Email Integrations",
      "Data Import and Export",
      "Multi-language Support",
      "Smart Dashboard",
      "Document Generation",
      "Workflow Automation",
      "Advanced Permissions",
      "Audit Logging",
      "Daily Backup",
      "White Label",
      "System Customization",
      "Unlimited Chat Support (1 hr)",
      "Live Onboarding Training",
    ],
  },
];
